### ISSUE TITLE
How to load non-twitter emojis?

### ISSUE THREAD

**Issue by PaiJi** [DailyBotHQ/universal-emoji-parser#218]
It seems  `twemoji.maxcdn.com` have been the default src, if i want to specify to `Microsoft Team Emoji`, what should i do?

**Comment by xergioalex** [comment]
I release the v2 of the Universal Emoji Parser. The emojis were updated from PNGs to SVGs, and the styles were improved. Please take a look at the improvements.

About the CDN, you can also specify custom CDNs.

Please take a look at the documentation in the README:

- DEFAULT EMOJI CDN => `https://cdn.jsdelivr.net/gh/jdecked/twemoji@latest/assets/svg/`

| Option Name      | Type    | Default             | Description                                                                                                           |
| :--------------- | :------ | :------------------ | :-------------------------------------------------------------------------------------------------------------------- |
| emojiCDN         | string  | `DEFAULT EMOJI CDN` | Allow customize the emojis CDN. The `parseToHtml` option should be `true` to apply this option.                       |
| parseToHtml      | boolean | `true`              | Parse emojis unicodes and shortcodes into html images.                                                                |
| parseToUnicode   | boolean | `false`             | Parse emojis shortcodes into unicodes. The option **parseToHtml** should be `false` to apply.                         |
| parseToShortcode | boolean | `false`             | Parse emojis unicodes into shortcodes. The options **parseToHtml** and **parseToUnicode** should be `false` to apply. |

```
→ uEmojiParser.parse('Hello world! 😎 🚀', { emojiCDN: "https://custom.emoji.cdn/gh/jdecked/twemoji@latest/assets/svg/" })
Hello world! <img class="emoji" alt="😎" src="https://custom.emoji.cdn/gh/jdecked/twemoji@latest/assets/svg/1f60e.svg"/> <img class="emoji" alt="🚀" src="https://custom.emoji.cdn/gh/jdecked/twemoji@latest/assets/svg/1f680.svg"/>
```
