### ISSUE TITLE
New versions of Twemoji

### ISSUE THREAD

**Issue by XtoManuel** [DailyBotHQ/universal-emoji-parser#219]
Twemoji has received some new updates, and is in a new repository: https://github.com/jdecked/twemoji
\[Information from: https://emojipedia.org/twitter \]

With this new version, the URL to obtain the emoji image is:
- https://cdn.jsdelivr.net/gh/jdecked/twemoji@latest/assets/72x72/2764.png (Latest version)
- https://cdn.jsdelivr.net/gh/jdecked/twemoji@14.0.2/assets/72x72/2764.png (A specific version, such as `14.0.2`)

**Comment by xergioalex** [comment]
Thanks for your advice, I will check this new version and apply it into this package as soon as possible.

**Comment by xergioalex** [comment]
I released the v2 of the universal-emoji-parser upgrading twemoji and other relevant libraries like emojilib and unicode-emoji-json.

Now the emojis have switched from PNGs to SVGs and many more emojis are supported than before.

Thanks for your contribution.
