### ISSUE TITLE
Allow formatting of GitHub emojis.

### ISSUE THREAD

**Issue by XtoManuel** [DailyBotHQ/universal-emoji-parser#220]
The format of GitHub :emojis: are not parsed correctly.
For example:
![imagen](https://github.com/DailyBotHQ/universal-emoji-parser/assets/25475587/98f335fa-828c-45bd-b1ee-2a0fe736bc6a)

**Comment by xergioalex** [comment]
Thank you for your notice. I am working on several improvements to support many more emojis, as many new emojis have been released that are currently not supported.

For now, I have resolved the emojis that you suggested in this pull request:
https://github.com/DailyBotHQ/universal-emoji-parser/pull/228/files

Thank you again for your contribution.

**Comment by XtoManuel** [comment]
The above is an example, but it happens with many more emojis, I show a text in code as shown and how it is seen on the web.

![image](https://github.com/DailyBotHQ/universal-emoji-parser/assets/25475587/571bf1df-0862-49ca-aa2a-c63135badf12)
![image](https://github.com/DailyBotHQ/universal-emoji-parser/assets/25475587/c494c356-5c63-4d2d-b4f3-d1d93a3bd94a)

Is it also possible to define in some way the origin of the emoji code? There are emojis that are different depending on the origin. For example `:pencil:`
`:pencil: (GitHub, Slack, Discord)` -> 📝
`:pencil: (Emojipedia)` -> ✏️
