### ISSUE TITLE
CDN twemoji.maxcdn.com down

### ISSUE THREAD

**Issue by offaxis** [DailyBotHQ/universal-emoji-parser#39]
Hi !

It seems the cdn of emoji images is down since yesterday (2022/01/09 5PM GMT), is there an alternative to get those images ? Do you have any updates from them ?

Thanks

**Comment by offaxis** [comment]
twemoji has added a patch to edit images url, can you update your package when they released the correction ?

**Comment by xergioalexpro** [comment]
Hi @offaxis, thanks for letting me know this. I will work on the fix as soon as possible.

**Comment by xergioalex** [comment]
I released a hotfix updating the CDN.
 I will add a setting to allow configure a custom CDN in the next release.

**Comment by offaxis** [comment]
Thanks for your quick fix !
